name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  gut-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.3-stable_linux.x86_64
      - name: Add Godot to PATH
        run: echo "${{ github.workspace }}/godot" >> $GITHUB_PATH
      - name: Build and Run
        run: |
          cd Jogo
          echo "------------------------------------------LOAD----------------------------------------------------"
          timeout --preserve-status 10s Godot_v4.3-stable_linux.x86_64 --headless --no-window project.godot || true
          echo "-----------------------------------------RELOAD---------------------------------------------------" #necessário para carregar os assets que não vão de primeira
          timeout --preserve-status 5s Godot_v4.3-stable_linux.x86_64 --headless --no-window project.godot || true
          echo "------------------------------------------RUN-----------------------------------------------------"
          timeout --preserve-status 5s Godot_v4.3-stable_linux.x86_64 --headless --no-window || true
      - name: Run GUT Tests
        run: |
          cd Jogo
          Godot_v4.3-stable_linux.x86_64 --headless -s addons/gut/gut_cmdln.gd -d --path "$PWD" -gdir=res://tests -gexit
